# Generated by Django 4.2.16 on 2024-12-27 19:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_catalog', '0003_ingredient_cost_ingredient_raw_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Название должно быть текстом', regex='^[A-Za-zА-Яа-яёЁ\\s]+$')], verbose_name='Название единицы измерения')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Сокращение единицы измерения')),
                ('unit_grams', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Вес должен быть не меньше грамма')], verbose_name='Вес в граммах')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='raw_weight',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='weight',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель ингредиента'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Количество должно быть не меньше 1')], verbose_name='Количество ингредиента'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Цена должна быть не меньше 1 рубля')], verbose_name='Цена за единицу'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_catalog.measureunit', verbose_name='Единица измерения'),
        ),
    ]
